version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:21.7.2-browsers

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build app
          command: yarn build

  store_test_results:
    docker:
      - image: cimg/node:21.7.2-browsers

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
      - store_test_results:
          path: ~/project/test-results
          destination: test-results

  deploy:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Deploy to Render
          command: |
            curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${RENDER_API_KEY}" -d '{"branch":"main"}' https://api.render.com/deploy/srv-co62884f7o1s73aa7jr0?key=${RENDER_DEPLOY_HOOK}

workflows:
  build_and_test:
    jobs:
      - build
      - store_test_results:
          requires:
            - build
      - deploy:
          requires:
            - build
