version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build app
          command: yarn build

  store_test_results:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run tests
          command: yarn test

# Orchestrate jobs using workflows
workflows:
  project-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - say-hello
      - store_test_results:
          requires:
            - say-hello
